### ISSUE TITLE
[Feature Request] Corpse doesn't decay

### ISSUE THREAD

**Issue by Jomik** [Pyrofab/Dissolution#6]
Would it be possible to set or disable corpse decay?
That's one of my reasons for using grave mods, to ensure items don't disappear when you die.

**Comment by Pyrofab** [comment]
Added in 0.4.2

**Comment by Jomik** [comment]
@Pyrofab So this wont come to 1.11? 😢

**Comment by Pyrofab** [comment]
Well, I guess I have no other choice than backporting now, do I ? It will
probably be out in a few days.

Le 19 juil. 2017 11:20, "Jonas Damtoft" <notifications@github.com> a écrit :

@Pyrofab <https://github.com/pyrofab> So this wont come to 1.11? 😢

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Pyrofab/Dissolution/issues/6#issuecomment-316325221>,
or mute the thread

**Comment by Jomik** [comment]
Amazing, thank you! 😄

**Comment by Pyrofab** [comment]
Alright, it's done ! Go grab it while it's hot !
*or update to 1.12, that would be a good idea too*
