### ISSUE TITLE
Suggestions about possession

### ISSUE THREAD

**Issue by KingEdward9830** [Pyrofab/Dissolution#7]
Just a quick thought, maybe when you have XP left while possessing something its AI gets turned off until either you leave its body or run out of XP from the ghost drain. Also, if you ever get around to implementing hostile mob possession you could make it so that using mobs' abilities/attacks requires you to still have XP as well. For example, if you have XP and possess a skeleton you can fire its bow(assuming it has one) but no XP means you can't anymore. The general reasoning behind it is that if you can still remember your life, your will would be stronger, thus allowing greater control over things you possess.

**Comment by Pyrofab** [comment]
I will implement hostile mob possession, but there will be a bigger requirement than for passive mobs so that will probably not be quite soon. The additional control with some mobs is a great idea actually ! That said, I will maybe make it so the player can only choose the monster's target and it will attack by itself instead of case by case interaction. We will see.

**Comment by Pyrofab** [comment]
Hostile possession with total control added in 0.5.
